/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabula.vista;

/**
 *
 * @author MAR
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        lblPartidasGanadas = new javax.swing.JLabel();
        lblGanesLiebre = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();
        lblTortuga = new javax.swing.JLabel();
        lblLiebre = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();
        lblGanesTortuga = new javax.swing.JLabel();
        lblEstadoLiebre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(828, 515));
        setPreferredSize(new java.awt.Dimension(828, 515));
        setSize(new java.awt.Dimension(828, 515));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setFont(new java.awt.Font("Futura", 0, 15)); // NOI18N
        btnIniciar.setText("Iniciar Carrera!");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 136, 40));

        lblPartidasGanadas.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblPartidasGanadas.setText("Partidas Ganadas:");
        getContentPane().add(lblPartidasGanadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblGanesLiebre.setFont(new java.awt.Font("Futura", 1, 15)); // NOI18N
        lblGanesLiebre.setText("Jugador 1: 0");
        getContentPane().add(lblGanesLiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblGanador.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGanador.setText("Gana la Tortuga!");
        lblGanador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 300, 180, 110));

        lblTortuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/tortuga.png"))); // NOI18N
        lblTortuga.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 60, 70));

        lblLiebre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/liebre.png"))); // NOI18N
        getContentPane().add(lblLiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 60, 70));

        lblSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/separador2.png"))); // NOI18N
        lblSeparador.setFocusable(false);
        lblSeparador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSeparador.setIgnoreRepaint(true);
        getContentPane().add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 40, -1));

        lblPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/fondo.png"))); // NOI18N
        getContentPane().add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 640, 510));

        lblGanesTortuga.setFont(new java.awt.Font("Futura", 1, 15)); // NOI18N
        lblGanesTortuga.setText("Jugador 2: 0");
        getContentPane().add(lblGanesTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblEstadoLiebre.setFont(new java.awt.Font("Futura", 1, 15)); // NOI18N
        lblEstadoLiebre.setText("La liebre esta durmiendo");
        lblEstadoLiebre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        getContentPane().add(lblEstadoLiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        lblLiebre.setLocation(lblLiebre.getX() + 46,190);
        lblTortuga.setLocation(lblTortuga.getX() + 46,270);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblEstadoLiebre;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblGanesLiebre;
    private javax.swing.JLabel lblGanesTortuga;
    private javax.swing.JLabel lblLiebre;
    private javax.swing.JLabel lblPartidasGanadas;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTortuga;
    // End of variables declaration//GEN-END:variables
}
