/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabula.vista;

/**
 *
 * @author MAR
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblPartidasGanadas = new javax.swing.JLabel();
        lblPartidasGanadasJ1 = new javax.swing.JLabel();
        lblPartidasGanadasJ2 = new javax.swing.JLabel();
        lblTortuga = new javax.swing.JLabel();
        lblLiebre = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();

        btnJugar.setFont(new java.awt.Font("Futura", 0, 15)); // NOI18N
        btnJugar.setText("Jugar!");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(828, 515));
        setPreferredSize(new java.awt.Dimension(828, 515));
        setSize(new java.awt.Dimension(828, 515));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Futura", 1, 27)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("La Liebre y la Tortuga");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 304, 45));

        btnIniciar.setFont(new java.awt.Font("Futura", 0, 15)); // NOI18N
        btnIniciar.setText("Iniciar Carrera!");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 136, 40));

        lblPartidasGanadas.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblPartidasGanadas.setText("Partidas Ganadas:");
        getContentPane().add(lblPartidasGanadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblPartidasGanadasJ1.setFont(new java.awt.Font("Futura", 1, 15)); // NOI18N
        lblPartidasGanadasJ1.setText("Jugador 1: 0");
        getContentPane().add(lblPartidasGanadasJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblPartidasGanadasJ2.setFont(new java.awt.Font("Futura", 1, 15)); // NOI18N
        lblPartidasGanadasJ2.setText("Jugador 2: 0");
        getContentPane().add(lblPartidasGanadasJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblTortuga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/tortuga.png"))); // NOI18N
        lblTortuga.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTortuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 60, 70));

        lblLiebre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/liebre.png"))); // NOI18N
        getContentPane().add(lblLiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 60, 70));

        lblSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/separador2.png"))); // NOI18N
        lblSeparador.setFocusable(false);
        lblSeparador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSeparador.setIgnoreRepaint(true);
        getContentPane().add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 40, -1));

        lblPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabula/img/camino.png"))); // NOI18N
        getContentPane().add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 520, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        lblLiebre.setLocation(lblLiebre.getX() + 46,490);
        lblTortuga.setLocation(lblTortuga.getX() + 46,270);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel lblLiebre;
    private javax.swing.JLabel lblPartidasGanadas;
    private javax.swing.JLabel lblPartidasGanadasJ1;
    private javax.swing.JLabel lblPartidasGanadasJ2;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTortuga;
    // End of variables declaration//GEN-END:variables
}
